/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_qingwan_bluedove_Native */

#ifndef _Included_dev_qingwan_bluedove_Native
#define _Included_dev_qingwan_bluedove_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dev_qingwan_bluedove_Native
 * Method:    n_releaseObject
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_dev_qingwan_bluedove_Native_n_1releaseObject
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
