/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_qingwan_bluedove_BluetoothSignalStrengthFilter */

#ifndef _Included_dev_qingwan_bluedove_BluetoothSignalStrengthFilter
#define _Included_dev_qingwan_bluedove_BluetoothSignalStrengthFilter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dev_qingwan_bluedove_BluetoothSignalStrengthFilter
 * Method:    n_getInRangeThresholdInDBm
 * Signature: (J)S
 */
JNIEXPORT jshort JNICALL Java_dev_qingwan_bluedove_BluetoothSignalStrengthFilter_n_1getInRangeThresholdInDBm
  (JNIEnv *, jclass, jlong);

/*
 * Class:     dev_qingwan_bluedove_BluetoothSignalStrengthFilter
 * Method:    n_setInRangeThresholdInDBm
 * Signature: (JS)V
 */
JNIEXPORT void JNICALL Java_dev_qingwan_bluedove_BluetoothSignalStrengthFilter_n_1setInRangeThresholdInDBm
  (JNIEnv *, jclass, jlong, jshort);

/*
 * Class:     dev_qingwan_bluedove_BluetoothSignalStrengthFilter
 * Method:    n_getOutOfRangeThresholdInDBm
 * Signature: (J)S
 */
JNIEXPORT jshort JNICALL Java_dev_qingwan_bluedove_BluetoothSignalStrengthFilter_n_1getOutOfRangeThresholdInDBm
  (JNIEnv *, jclass, jlong);

/*
 * Class:     dev_qingwan_bluedove_BluetoothSignalStrengthFilter
 * Method:    n_setOutOfRangeThresholdInDBm
 * Signature: (JS)V
 */
JNIEXPORT void JNICALL Java_dev_qingwan_bluedove_BluetoothSignalStrengthFilter_n_1setOutOfRangeThresholdInDBm
  (JNIEnv *, jclass, jlong, jshort);

/*
 * Class:     dev_qingwan_bluedove_BluetoothSignalStrengthFilter
 * Method:    n_setOutOfRangeTimeout
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_dev_qingwan_bluedove_BluetoothSignalStrengthFilter_n_1setOutOfRangeTimeout
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     dev_qingwan_bluedove_BluetoothSignalStrengthFilter
 * Method:    n_getOutOfRangeTimeout
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_dev_qingwan_bluedove_BluetoothSignalStrengthFilter_n_1getOutOfRangeTimeout
  (JNIEnv *, jclass, jlong);

/*
 * Class:     dev_qingwan_bluedove_BluetoothSignalStrengthFilter
 * Method:    n_setSamplingInterval
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_dev_qingwan_bluedove_BluetoothSignalStrengthFilter_n_1setSamplingInterval
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     dev_qingwan_bluedove_BluetoothSignalStrengthFilter
 * Method:    n_getSamplingInterval
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_dev_qingwan_bluedove_BluetoothSignalStrengthFilter_n_1getSamplingInterval
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
