/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_qingwan_bluedove_BluetoothAdapter */

#ifndef _Included_dev_qingwan_bluedove_BluetoothAdapter
#define _Included_dev_qingwan_bluedove_BluetoothAdapter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dev_qingwan_bluedove_BluetoothAdapter
 * Method:    n_getDefaultAsync
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_dev_qingwan_bluedove_BluetoothAdapter_n_1getDefaultAsync
  (JNIEnv *, jclass);

/*
 * Class:     dev_qingwan_bluedove_BluetoothAdapter
 * Method:    n_releaseAdapter
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_dev_qingwan_bluedove_BluetoothAdapter_n_1releaseAdapter
  (JNIEnv *, jclass, jlong);

/*
 * Class:     dev_qingwan_bluedove_BluetoothAdapter
 * Method:    n_getDeviceId
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_dev_qingwan_bluedove_BluetoothAdapter_n_1getDeviceId
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
