/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_qingwan_bluedove_winrt_AsyncOperation */

#ifndef _Included_dev_qingwan_bluedove_winrt_AsyncOperation
#define _Included_dev_qingwan_bluedove_winrt_AsyncOperation
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dev_qingwan_bluedove_winrt_AsyncOperation
 * Method:    n_get
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_dev_qingwan_bluedove_winrt_AsyncOperation_n_1get
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
