/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_qingwan_bluedove_winrt_GUID */

#ifndef _Included_dev_qingwan_bluedove_winrt_GUID
#define _Included_dev_qingwan_bluedove_winrt_GUID
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dev_qingwan_bluedove_winrt_GUID
 * Method:    n_equals
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_dev_qingwan_bluedove_winrt_GUID_n_1equals
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
