/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_qingwan_bluedove_genericAttributeProfile_GattReadResult */

#ifndef _Included_dev_qingwan_bluedove_genericAttributeProfile_GattReadResult
#define _Included_dev_qingwan_bluedove_genericAttributeProfile_GattReadResult
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dev_qingwan_bluedove_genericAttributeProfile_GattReadResult
 * Method:    n_getValue
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_dev_qingwan_bluedove_genericAttributeProfile_GattReadResult_n_1getValue
  (JNIEnv *, jclass, jlong);

/*
 * Class:     dev_qingwan_bluedove_genericAttributeProfile_GattReadResult
 * Method:    n_getProtocolError
 * Signature: (J)B
 */
JNIEXPORT jbyte JNICALL Java_dev_qingwan_bluedove_genericAttributeProfile_GattReadResult_n_1getProtocolError
  (JNIEnv *, jclass, jlong);

/*
 * Class:     dev_qingwan_bluedove_genericAttributeProfile_GattReadResult
 * Method:    n_getStatus
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_dev_qingwan_bluedove_genericAttributeProfile_GattReadResult_n_1getStatus
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
