/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_qingwan_bluedove_advertisement_BluetoothLEAdvertisement */

#ifndef _Included_dev_qingwan_bluedove_advertisement_BluetoothLEAdvertisement
#define _Included_dev_qingwan_bluedove_advertisement_BluetoothLEAdvertisement
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dev_qingwan_bluedove_advertisement_BluetoothLEAdvertisement
 * Method:    n_getLocalName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_dev_qingwan_bluedove_advertisement_BluetoothLEAdvertisement_n_1getLocalName
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
