/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_qingwan_bluedove_BluetoothLEDevice */

#ifndef _Included_dev_qingwan_bluedove_BluetoothLEDevice
#define _Included_dev_qingwan_bluedove_BluetoothLEDevice
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dev_qingwan_bluedove_BluetoothLEDevice
 * Method:    n_fromIdAsync
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_dev_qingwan_bluedove_BluetoothLEDevice_n_1fromIdAsync
  (JNIEnv *, jclass, jstring);

/*
 * Class:     dev_qingwan_bluedove_BluetoothLEDevice
 * Method:    n_fromBluetoothAddressAsync
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_dev_qingwan_bluedove_BluetoothLEDevice_n_1fromBluetoothAddressAsync
  (JNIEnv *, jclass, jlong);

/*
 * Class:     dev_qingwan_bluedove_BluetoothLEDevice
 * Method:    n_getName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_dev_qingwan_bluedove_BluetoothLEDevice_n_1getName
  (JNIEnv *, jclass, jlong);

/*
 * Class:     dev_qingwan_bluedove_BluetoothLEDevice
 * Method:    n_getDeviceId
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_dev_qingwan_bluedove_BluetoothLEDevice_n_1getDeviceId
  (JNIEnv *, jclass, jlong);

/*
 * Class:     dev_qingwan_bluedove_BluetoothLEDevice
 * Method:    n_getGattServicesAsync
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_dev_qingwan_bluedove_BluetoothLEDevice_n_1getGattServicesAsync
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
