/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_qingwan_bluedove_genericAttributeProfile_GattCharacteristicsResult */

#ifndef _Included_dev_qingwan_bluedove_genericAttributeProfile_GattCharacteristicsResult
#define _Included_dev_qingwan_bluedove_genericAttributeProfile_GattCharacteristicsResult
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dev_qingwan_bluedove_genericAttributeProfile_GattCharacteristicsResult
 * Method:    n_getCharacteristics
 * Signature: (J)[J
 */
JNIEXPORT jlongArray JNICALL Java_dev_qingwan_bluedove_genericAttributeProfile_GattCharacteristicsResult_n_1getCharacteristics
  (JNIEnv *, jclass, jlong);

/*
 * Class:     dev_qingwan_bluedove_genericAttributeProfile_GattCharacteristicsResult
 * Method:    n_getProtocolError
 * Signature: (J)B
 */
JNIEXPORT jbyte JNICALL Java_dev_qingwan_bluedove_genericAttributeProfile_GattCharacteristicsResult_n_1getProtocolError
  (JNIEnv *, jclass, jlong);

/*
 * Class:     dev_qingwan_bluedove_genericAttributeProfile_GattCharacteristicsResult
 * Method:    n_getStatus
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_dev_qingwan_bluedove_genericAttributeProfile_GattCharacteristicsResult_n_1getStatus
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
