/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_qingwan_bluedove_BluetoothLEDevice */

#ifndef _Included_dev_qingwan_bluedove_BluetoothLEDevice
#define _Included_dev_qingwan_bluedove_BluetoothLEDevice
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dev_qingwan_bluedove_BluetoothLEDevice
 * Method:    n_fromIdAsync
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_dev_qingwan_bluedove_BluetoothLEDevice_n_1fromIdAsync
  (JNIEnv *, jclass, jstring);

/*
 * Class:     dev_qingwan_bluedove_BluetoothLEDevice
 * Method:    n_releaseDevice
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_dev_qingwan_bluedove_BluetoothLEDevice_n_1releaseDevice
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
