/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_qingwan_bluedove_genericAttributeProfile_GattCharacteristic */

#ifndef _Included_dev_qingwan_bluedove_genericAttributeProfile_GattCharacteristic
#define _Included_dev_qingwan_bluedove_genericAttributeProfile_GattCharacteristic
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dev_qingwan_bluedove_genericAttributeProfile_GattCharacteristic
 * Method:    n_getUuid
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_dev_qingwan_bluedove_genericAttributeProfile_GattCharacteristic_n_1getUuid
  (JNIEnv *, jclass, jlong);

/*
 * Class:     dev_qingwan_bluedove_genericAttributeProfile_GattCharacteristic
 * Method:    n_readValueAsync
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_dev_qingwan_bluedove_genericAttributeProfile_GattCharacteristic_n_1readValueAsync
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
