/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_qingwan_bluedove_genericAttributeProfile_GattDeviceService */

#ifndef _Included_dev_qingwan_bluedove_genericAttributeProfile_GattDeviceService
#define _Included_dev_qingwan_bluedove_genericAttributeProfile_GattDeviceService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dev_qingwan_bluedove_genericAttributeProfile_GattDeviceService
 * Method:    n_getUuid
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_dev_qingwan_bluedove_genericAttributeProfile_GattDeviceService_n_1getUuid
  (JNIEnv *, jclass, jlong);

/*
 * Class:     dev_qingwan_bluedove_genericAttributeProfile_GattDeviceService
 * Method:    n_getCharacteristicsAsync
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_dev_qingwan_bluedove_genericAttributeProfile_GattDeviceService_n_1getCharacteristicsAsync
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
