/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_qingwan_bluedove_BluetoothUuidHelper */

#ifndef _Included_dev_qingwan_bluedove_BluetoothUuidHelper
#define _Included_dev_qingwan_bluedove_BluetoothUuidHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dev_qingwan_bluedove_BluetoothUuidHelper
 * Method:    n_fromShortId
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_dev_qingwan_bluedove_BluetoothUuidHelper_n_1fromShortId
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
