/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_qingwan_bluedove_advertisement_BluetoothLEAdvertisementWatcher */

#ifndef _Included_dev_qingwan_bluedove_advertisement_BluetoothLEAdvertisementWatcher
#define _Included_dev_qingwan_bluedove_advertisement_BluetoothLEAdvertisementWatcher
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dev_qingwan_bluedove_advertisement_BluetoothLEAdvertisementWatcher
 * Method:    n_newWatcher
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_dev_qingwan_bluedove_advertisement_BluetoothLEAdvertisementWatcher_n_1newWatcher
  (JNIEnv *, jclass);

/*
 * Class:     dev_qingwan_bluedove_advertisement_BluetoothLEAdvertisementWatcher
 * Method:    n_getStatus
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_dev_qingwan_bluedove_advertisement_BluetoothLEAdvertisementWatcher_n_1getStatus
  (JNIEnv *, jclass, jlong);

/*
 * Class:     dev_qingwan_bluedove_advertisement_BluetoothLEAdvertisementWatcher
 * Method:    n_listenReceived
 * Signature: (JLdev/qingwan/bluedove/advertisement/BluetoothLEAdvertisementWatcher/BluetoothLEAdvertisementReceivedListener;)J
 */
JNIEXPORT jlong JNICALL Java_dev_qingwan_bluedove_advertisement_BluetoothLEAdvertisementWatcher_n_1listenReceived
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     dev_qingwan_bluedove_advertisement_BluetoothLEAdvertisementWatcher
 * Method:    n_start
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_dev_qingwan_bluedove_advertisement_BluetoothLEAdvertisementWatcher_n_1start
  (JNIEnv *, jclass, jlong);

/*
 * Class:     dev_qingwan_bluedove_advertisement_BluetoothLEAdvertisementWatcher
 * Method:    n_stop
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_dev_qingwan_bluedove_advertisement_BluetoothLEAdvertisementWatcher_n_1stop
  (JNIEnv *, jclass, jlong);

/*
 * Class:     dev_qingwan_bluedove_advertisement_BluetoothLEAdvertisementWatcher
 * Method:    n_revokeReceivedListener
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_dev_qingwan_bluedove_advertisement_BluetoothLEAdvertisementWatcher_n_1revokeReceivedListener
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     dev_qingwan_bluedove_advertisement_BluetoothLEAdvertisementWatcher
 * Method:    n_setScanningMode
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_dev_qingwan_bluedove_advertisement_BluetoothLEAdvertisementWatcher_n_1setScanningMode
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     dev_qingwan_bluedove_advertisement_BluetoothLEAdvertisementWatcher
 * Method:    n_getScanningMode
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_dev_qingwan_bluedove_advertisement_BluetoothLEAdvertisementWatcher_n_1getScanningMode
  (JNIEnv *, jclass, jlong);

/*
 * Class:     dev_qingwan_bluedove_advertisement_BluetoothLEAdvertisementWatcher
 * Method:    n_getSignalStrengthFilter
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_dev_qingwan_bluedove_advertisement_BluetoothLEAdvertisementWatcher_n_1getSignalStrengthFilter
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
