/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_qingwan_bluedove_advertisement_BluetoothLEAdvertisementWatcher_BluetoothLEAdvertisementReceivedEventArgs */

#ifndef _Included_dev_qingwan_bluedove_advertisement_BluetoothLEAdvertisementWatcher_BluetoothLEAdvertisementReceivedEventArgs
#define _Included_dev_qingwan_bluedove_advertisement_BluetoothLEAdvertisementWatcher_BluetoothLEAdvertisementReceivedEventArgs
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dev_qingwan_bluedove_advertisement_BluetoothLEAdvertisementWatcher_BluetoothLEAdvertisementReceivedEventArgs
 * Method:    n_getBluetoothAddress
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_dev_qingwan_bluedove_advertisement_BluetoothLEAdvertisementWatcher_00024BluetoothLEAdvertisementReceivedEventArgs_n_1getBluetoothAddress
  (JNIEnv *, jclass, jlong);

/*
 * Class:     dev_qingwan_bluedove_advertisement_BluetoothLEAdvertisementWatcher_BluetoothLEAdvertisementReceivedEventArgs
 * Method:    n_getAdvertisement
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_dev_qingwan_bluedove_advertisement_BluetoothLEAdvertisementWatcher_00024BluetoothLEAdvertisementReceivedEventArgs_n_1getAdvertisement
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
